DROP TABLE LETTERB;
create table LETTERB AS
(
	SELECT DEL.ROW_ID, DEL.ORDER_ID, DEL.ORDER_DATE, DEL.SHIP_DATE,  
    DEL.CITY AS LOCATION, 
    DEL.PRODUCT_NAME, 
    DEL.SALES, DEL.QUANTITY, DEL.DISCOUNT,DEL.PROFIT, 
    OTD.TIME_KEY,     
    OTD.PARENT_ID, 
    OTD.TIME_DESC
FROM DELIVERIES DEL 
RIGHT OUTER JOIN OSS_TIME_DIM OTD
ON 
	DEL.SHIP_DATE = OTD.TIME_DESC
);

DROP TABLE LET_B;
CREATE TABLE LET_B AS 
SELECT PARENT_ID AS MON, SUM(SALES) AS TOTAL_SALES FROM LETTERB WHERE  (SHIP_DATE LIKE '%2015' AND PARENT_ID LIKE 'M%') GROUP BY PARENT_ID;

SELECT MON,OTD.TIME_DESC, TOTAL_SALES FROM LET_B B1
FULL OUTER JOIN OSS_TIME_DIM OTD
ON B1.MON= OTD.TIME_KEY
WHERE TOTAL_SALES=(SELECT MAX(TOTAL_SALES) FROM LET_B);
