DROP TABLE LETTERD;
create table LETTERD AS
(
	SELECT DEL.ROW_ID, DEL.ORDER_ID, DEL.ORDER_DATE, DEL.SHIP_DATE,  
    DEL.CITY AS LOCATION, 
    DEL.PRODUCT_NAME, 
    DEL.SALES, DEL.QUANTITY, DEL.DISCOUNT,DEL.PROFIT, 
    OTD.TIME_KEY,     
    OTD.PARENT_ID, 
    OTD.TIME_DESC
FROM DELIVERIES DEL 
RIGHT OUTER JOIN OSS_TIME_DIM OTD
ON 
	DEL.SHIP_DATE = OTD.TIME_DESC
);

DROP TABLE LET_D;
CREATE TABLE LET_D AS 
SELECT PARENT_ID AS MON, PRODUCT_NAME, SUM(QUANTITY) AS QTY_SOLD FROM LETTERD WHERE  (SHIP_DATE LIKE '%2015' AND PARENT_ID LIKE 'M%' AND LOCATION='New York City') GROUP BY PRODUCT_NAME,PARENT_ID ORDER BY QTY_SOLD, MON DESC;

SELECT OTD.TIME_DESC as MONTH_,D1.PRODUCT_NAME, D1.QTY_SOLD AS QTY_SOLD FROM 
(LET_D D1 LEFT OUTER JOIN OSS_TIME_DIM OTD
ON D1.MON= OTD.TIME_KEY);