DROP TABLE LETTERE;
create table LETTERE AS
(
	SELECT DEL.ROW_ID, DEL.ORDER_ID, DEL.ORDER_DATE, DEL.SHIP_DATE,  
    DEL.CITY AS LOCATION, 
    DEL.PRODUCT_NAME, 
    DEL.SALES, DEL.QUANTITY, DEL.DISCOUNT,DEL.PROFIT, 
    OTD.TIME_KEY,     
    OTD.PARENT_ID, 
    OTD.TIME_DESC
FROM DELIVERIES DEL 
RIGHT OUTER JOIN OSS_TIME_DIM OTD
ON 
	DEL.SHIP_DATE = OTD.TIME_DESC
);

DROP TABLE LET_E;
CREATE TABLE LET_E AS 
SELECT PARENT_ID AS MON, PRODUCT_NAME, SUM(QUANTITY) AS QTY_SOLD_SALES,SUM(PROFIT) AS PROFIT_GENERATED FROM LETTERE WHERE  (SHIP_DATE LIKE '%2015' AND PARENT_ID LIKE 'M%') GROUP BY PRODUCT_NAME,PARENT_ID ORDER BY PROFIT_GENERATED DESC;

DROP TABLE LET_E2;
CREATE TABLE LET_E2 AS(
SELECT OTD.PARENT_ID AS QUARTER,E1.PRODUCT_NAME, (E1.QTY_SOLD_SALES) AS QTY_SOLD_SALES, (E1.PROFIT_GENERATED) AS PROFIT_GENERATED FROM 
(LET_E E1 LEFT OUTER JOIN OSS_TIME_DIM OTD
ON E1.MON= OTD.TIME_KEY)
);

SELECT * FROM(
SELECT QUARTER, PRODUCT_NAME, SUM(QTY_SOLD_SALES) AS QTY_SOLD_SALES, SUM(PROFIT_GENERATED) AS PROFIT_GENERATED
FROM LET_E2
WHERE QUARTER='Q01'
GROUP BY PRODUCT_NAME,QUARTER ORDER BY QUARTER
)WHERE ROWNUM <=3
UNION
SELECT * FROM(
SELECT QUARTER, PRODUCT_NAME, SUM(QTY_SOLD_SALES) AS QTY_SOLD_SALES, SUM(PROFIT_GENERATED) AS PROFIT_GENERATED
FROM LET_E2
WHERE QUARTER='Q02'
GROUP BY PRODUCT_NAME,QUARTER ORDER BY QUARTER
)WHERE ROWNUM <=3
UNION
SELECT * FROM(
SELECT QUARTER, PRODUCT_NAME, SUM(QTY_SOLD_SALES) AS QTY_SOLD_SALES, SUM(PROFIT_GENERATED) AS PROFIT_GENERATED
FROM LET_E2
WHERE QUARTER='Q03'
GROUP BY PRODUCT_NAME,QUARTER ORDER BY QUARTER
)WHERE ROWNUM <=3
UNION
SELECT * FROM(
SELECT QUARTER, PRODUCT_NAME, SUM(QTY_SOLD_SALES) AS QTY_SOLD_SALES, SUM(PROFIT_GENERATED) AS PROFIT_GENERATED
FROM LET_E2
WHERE QUARTER='Q04'
GROUP BY PRODUCT_NAME,QUARTER ORDER BY QUARTER
)WHERE ROWNUM <=3;
