DROP TABLE LETTERF;
create table LETTERF AS
(
	SELECT DEL.ROW_ID, DEL.ORDER_ID, DEL.ORDER_DATE, DEL.SHIP_DATE,  
    DEL.CITY, 
    DEL.PRODUCT_NAME, 
    DEL.SALES, DEL.QUANTITY, DEL.DISCOUNT,DEL.PROFIT, 
    OTD.TIME_KEY,     
    OTD.PARENT_ID, 
    OTD.TIME_DESC
FROM DELIVERIES DEL 
RIGHT OUTER JOIN OSS_TIME_DIM OTD
ON 
	DEL.SHIP_DATE = OTD.TIME_DESC
);

DROP TABLE LET_F;
CREATE TABLE LET_F AS 
SELECT PARENT_ID AS MON, PRODUCT_NAME,CITY, SUM(QUANTITY) AS QTY_SOLD_SALES FROM LETTERF WHERE  (SHIP_DATE LIKE '%2015' AND PARENT_ID LIKE 'M%') GROUP BY CITY,PRODUCT_NAME,PARENT_ID,QUANTITY ORDER BY  QTY_SOLD_SALES DESC;

DROP TABLE LET_F2;
CREATE TABLE LET_F2 AS(
SELECT OTD.PARENT_ID AS QUARTER,F1.PRODUCT_NAME, CITY,(F1.QTY_SOLD_SALES) AS QTY_SOLD_SALES FROM 
LET_F F1 LEFT OUTER JOIN OSS_TIME_DIM OTD
ON F1.MON= OTD.TIME_KEY)
;


SELECT * FROM(
SELECT QUARTER, CITY AS LOCATION, SUM(QTY_SOLD_SALES) AS QTY_SOLD
FROM LET_F2
WHERE QUARTER='Q02'
GROUP BY PRODUCT_NAME,QUARTER,CITY ORDER BY QTY_SOLD DESC
)WHERE ROWNUM <=1
UNION
SELECT * FROM(
SELECT QUARTER, CITY AS LOCATION, SUM(QTY_SOLD_SALES) AS QTY_SOLD
FROM LET_F2
WHERE QUARTER='Q03'
GROUP BY PRODUCT_NAME,QUARTER,CITY ORDER BY QTY_SOLD DESC
)WHERE ROWNUM <=1;